name: Code Format Check

on: [push, pull_request]

jobs:
  format:
    name: Code Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

      - name: Trigger Test Workflow
        if: success()
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: test-cli.yml
          token: ${{ secrets.GITHUB_TOKEN }}